#!/bin/bash

CMD=${0##*/}
DIR=${0%/*}

OUTDIR=$(realpath $DIR)

BUILD=build
BUILD9=$BUILD/splice9

set -e

# TODO: copy to separate directory, remove ".fn*" and "*~" files
# TODO: fixup plugin/splice.vim to automaticaly change targets for release.

#
# Runs in the directory where "zipit" is found.
# This is the top of the Splice9 source tree.
#

cd $OUTDIR
rm -rf $BUILD
mkdir -p $BUILD9

cp -a {plugin,doc,autoload} $BUILD9
rm -f $BUILD9/autoload/splice9/rlib

rm $(find $BUILD9 -name '*~')

rm $BUILD9/doc/tags
vim -u NONE -c ":helptags $BUILD9/doc" -c ":quit"

# grab the string in quotes
version=$(grep '^export.*splice9_string_version' plugin/splice.vim \
                    | sed -E 's/^.*"(.+)".*$/\1/')

if [[ -z "$version" ]]
then
    echo "Version number not found. Cannot package splice9 release zip" 2>&1
    exit 1
fi

#echo "version:" $version $OUTDIR

cd $BUILD
zip -q -r $OUTDIR/splice9-$version.zip splice9

#jar -Mcvf splice9/splice9-$version.zip splice9/{plugin,doc,autoload}

