#!/bin/bash

CMD=${0##*/}
DIR=${0%/*}

set -e

# TODO: copy to separate directory, remove ".fn*" and "*~" files
# TODO: fixup plugin/splice.vim to automaticaly change targets for release.

#
# Runs in the directory where "zipit" if found.
# This is the top of the Splice9 source tree.
#

cd $DIR
#rm -f doc/tags

# grab the string in quotes
version=$(grep '^export.*splice9_string_version' plugin/splice.vim \
                    | sed -E 's/^.*"(.+)".*$/\1/')

if [[ -z "$version" ]]
then
    echo "Version number not found. Cannot package splice9 release zip" 2>&1
    exit 1
fi

cd .. 

jar -Mcvf splice9/splice9-$version.zip splice9/{plugin,doc,autoload}

